### ISSUE TITLE
[Feature] Create a Login/ Register Page

### ISSUE THREAD

**Issue by nishaaannnt** [gdscpce/hacktoberfest-event-spirit#5]
Create a Login and Register Page for the website.

1. Follow the design and color scheme
2. Make necessary input and label for the form
3. Pages should be accessed by the navbar

Comment your name, year and branch to get this issue assigned to you

**Comment by munirsiddiqui54** [comment]
I want to work on this issue.  please assign it to me
Munir SY IT

**Comment by nishaaannnt** [comment]
Go for it @munirsiddiqui54 
Please follow all the guidelines and steps for successful merge.
Also provide Screenshots of implementation while raising the PR
